language: python
python:
  - 3.5.2
install:
  - pip install -r requirements.txt
  - pip install coveralls 
  - pip install nose
before_script:
  - psql -c "CREATE DATABASE weconnect_test;" -U postgres
  - psql -c "CREATE USER weconnect WITH PASSWORD 'weconnect';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE weconnect_test TO weconnect;" -U postgres  
script:
  - nosetests --with-coverage --cover-package=app
after_success:
  - coveralls